### ISSUE TITLE
addListener hasn't handled undefined actionClass

### ISSUE THREAD

**Issue by DovydasNavickas** [SimplrJS/action-emitter#1]
If developer gives a non-existent `actionClass` to an `addListener` as a first parameter, it says:
```
TypeError: Right-hand side of 'instanceof' is not an object
```
It would be nice if this would be handled and would give a nice error saying:
```
Given `actionClass` is not a proper object.
```

Same thing for handler, if it's not handled yet.

**Comment by GiedriusGrabauskas** [comment]
Added runtime type checks.
